### ISSUE TITLE
Generate Prometheus extension from file

### ISSUE THREAD

**Issue by vbalbp** [dynatrace-extensions/dynatrace-extensions-vscode#109]
**Summary**
Sometimes we don't have access to the Prometheus server but instead we have an output example in a file. I think it would be useful to be able to also parse the Prometheus output from a file.

**Details**
I would imagine the feature would work as the current scrape we have for an endpoinmt, but instead you can just choose a file. If the file is the correct format, you get the prometheus extension auto-filled, just like the scrape one.

**Use Cases**
When creating an extension for a customer, we don't always have access to the customer's environment to fetch the data, however, we can get an example output from them sent to us, in a file.

**Challenges**
It should be fairly simple to adapt the current scraper to look at the data from a file instead of from an endpoint. The scrape logic is exactly the same, it just changes the input.

**Comment by radu-stefan-dt** [comment]
closed as part of 2.0.0
