### ISSUE TITLE
Uninstall/Disable of Copilot disables/uninstalls YAML extension 

### ISSUE THREAD

**Issue by PatrikSteuer** [dynatrace-extensions/dynatrace-extensions-vscode#115]
**Describe the bug**
When uninstalling/disabling copilot the YAML extension will also be deleted, which causes issue for other VSCode extensions.

**Steps to reproduce**
1. Have the `Dynatrace Extensions Copilot` + `ms-kubernetes-tools.vscode-kubernetes-tools` installed
2. Go to 'VSCode > Extensions'
3. Search for 'Dynatrace Extensions' and select it
3. Click on 'Disable'
```Cannot disable 'YAML' extension alone. 'Kubernetes' extension depends on this. Do you want to disable all these extensions?```
<img width="367" alt="image" src="https://github.com/dynatrace-extensions/dynatrace-extensions-copilot/assets/14013148/f63dc1d2-dacf-4b36-ba9a-596021d477b4">

**Expected behavior**
Disabling should disable only Copilot not the YAML extension, since it is used in many places. 
Same applies for deletion.

**Comment by radu-stefan-dt** [comment]
Hi @PatrikSteuer - thanks for raising this issue.

Until we find a proper solution, are you able to test this workaround:
1. Follow steps 1-4 and choose "Disable All"
2. Enable only the Kubernetes extension

**Comment by PatrikSteuer** [comment]
Hi @radu-stefan-dt,
I removed the extension already by removing the entry within 
```.vscode/extensions/extensions.json```
and by removing
.vscode/extensions/dynatraceplatformextensions.dt-ext-copilot-1.2.3-darwin-x64

So I am unable to validate the workaround.
