### ISSUE TITLE
Use dynatrace-api-client for API access

### ISSUE THREAD

**Issue by airborn** [dynatrace-extensions/dynatrace-extensions-vscode#17]
From what I can see the current implementation recreates part of the Dynatrace API. It may be helpful to replace this with the existing library that should expose the whole(?) API in TS:

https://www.npmjs.com/package/@dt-esa/dynatrace-api-client

**Comment by radu-stefan-dt** [comment]
Closing this ticket as "won't do".
With the move to new platform, this ticket is no longer as relevant. Investment in legacy APIs will be kept at a minimum.
