### ISSUE TITLE
2.4.0 and 2.4.1 signing issue

### ISSUE THREAD

**Issue by osd42** [dynatrace-extensions/dynatrace-extensions-vscode#173]
Hello,

**Since version 2.4.0 I cannot sign my extension v2**
using WSL 2 + latest vscode, since major update 2.4 I cannot sign my extensions.

**Steps to reproduce**
- install 2.4.0, build : during upload we get the message "Extension upload failed" and "Extension signature is not valid"
- install 2.4.1 with same process and errors
- rollback to 2.3.2 => upload + signature OK

**Screenshots or YAML snippet**
![image](https://github.com/dynatrace-extensions/dynatrace-extensions-vscode/assets/49947845/621732b4-e537-4d7f-9c4a-173f5f8604d2)

**Comment by radu-stefan-dt** [comment]
Hi @osd42. Thanks for reporting this. 

Could you please reproduce the error, then run the command "Download support archive" and attach the resulting .zip to this ticket?

Alternatively, you can just copy the content of the "Dynatrace Log" output channel (bottom part of the editor, output tab, dropdown on the right-hand side) and attach that as a file?

**Comment by radu-stefan-dt** [comment]
As well, could you please provide details of you WSL sub-system such as O/S name and version?
Thanks

**Comment by osd42** [comment]
Hi @radu-stefan-dt ,

There is no message in Dynatrace log. 
Here is the support archive zip file (last execution tested with version 2.4.1).
[support_archive.zip](https://github.com/dynatrace-extensions/dynatrace-extensions-vscode/files/13859750/support_archive.zip)

**vscode**
version: 1.85.1

**WSL details:**
`PS C:\> wsl --version
Version WSL : 2.0.9.0
Version du noyau (kernel) : 5.15.133.1-1
Version WSLg : 1.0.59
Version MSRDC : 1.2.4677
Version direct3D : 1.611.1-81528511
Version de DXCore : 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Version de Windows : 10.0.22621.2861
PS C:\> wsl -l -v
  NAME      STATE           VERSION
* Debian    Running         2`

**Windows (Hosting wsl):**
OS Name:              Microsoft Windows 11 Entreprise
OS Version:            10.0.22621 N/A build 22621

**Certificates configuration**
About the certificates: I use only "workspace" level certificates.

Thank you.

**Comment by radu-stefan-dt** [comment]
Ok. I can definitely see an issue with the flow of events.

The command starts off by building extension `custom:com.renault.extension.solace` with version `0.7.3`:

```log
2024-01-08T12:00:01.751Z [INFO][commandPalette.buildExtension.buildExtension] Executing Build Extension command
2024-01-08T12:00:01.752Z [DEBUG][] Normalizing extension version "0.7.3"
2024-01-08T12:00:01.752Z [DEBUG][utils.extensionParsing.normalizeExtensionVersion] Normalized as "0.7.3"
2024-01-08T12:00:01.980Z [DEBUG][commandPalette.buildExtension.buildExtension] Building package for a non-python extension
```

Then clean-up happens, and the upload command is triggered. The upload command will take the most recent file it finds in `dist` folder. Somehow it's ending up with:

```log
2024-01-08T12:00:05.836Z [INFO][commandPalette.uploadExtension] Executing Upload Extension command
2024-01-08T12:00:05.837Z [DEBUG][commandPalette.uploadExtension] Zip file for upload is custom_my.second.extension-0.0.1.zip
```

I believe the clean-up might be removing the youngest files from dist instead of the oldest ones.

**Comment by radu-stefan-dt** [comment]
I will validate and patch this ASAP.

In the meantime, as a short-term workaround, could you please add the following setting to either your global or workspace settings:

```json
{
    "dynatraceExtensions.maxBuildFiles": 0
}
```

This will disable the clean-up of the `dist` folder and you should be able to continue working until the issue is patched.

**Comment by osd42** [comment]
@radu-stefan-dt , I tested 2.4.2 with parameter "dynatraceExtensions.maxBuildFiles": 0 : it works !

Thank you !
