### ISSUE TITLE
Add environment - unable to verify the first certificate

### ISSUE THREAD

**Issue by sschmischke** [dynatrace-extensions/dynatrace-extensions-vscode#185]
When trying to connect to Dynatrace Managed environment I get:

`[ERROR][utils.conditionCheckers.checkUrlReachable] {"message":"unable to verify the first certificate","name":"Error","stack":"Error: unable to verify the first certificate\n\tat cc.from (c:\\Users\\XXX\\.vscode\\extensions\\dynatraceplatformextensions.dynatrace-extensions-2.4.3-win32-x64\\out\\main.js:183:30899)\n\tat Hr.<anonymous> (c:\\Users\\XXX\\.vscode\\extensions\\dynatraceplatformextensions.dynatrace-extensions-2.4.3-win32-x64\\out\\main.js:186:8864)\n\tat Hr.emit (node:events:513:28)\n\tat Dx.<computed> (c:\\Users\\XXX\\.vscode\\extensions\\dynatraceplatformextensions.dynatrace-extensions-2.4.3-win32-x64\\out\\main.js:6:883)\n\tat ClientRequest.emit (node:events:525:35)\n\tat TLSSocket.socketErrorListener (node:_http_client:481:9)\n\tat TLSSocket.emit (node:events:513:28)\n\tat emitErrorNT (node:internal/streams/destroy:157:8)\n\tat emitErrorCloseNT (node:internal/streams/destroy:122:3)\n\tat process.processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","User-Agent":"axios/1.6.3","Accept-Encoding":"gzip, compress, deflate, br"},"method":"get","url":"XXX/api/v1/time"},"code":"UNABLE_TO_VERIFY_LEAF_SIGNATURE","status":null}`

Can't find any solution for this VSCode extension to trust self signed certificates in documentation.

**Comment by radu-stefan-dt** [comment]
The extension doesn't define any special trust for certificates. As Microsoft documents [here](https://code.visualstudio.com/docs/setup/network#_ssl-certificates), VSCode uses the same trust store as Chromium, and this is the Operating System's trust store.

Does your browser see your certificate as valid?

Could you share a screenshot of the certificate details from the browser?

Example:
![image](https://github.com/dynatrace-extensions/dynatrace-extensions-vscode/assets/16157796/7d4db2e3-0028-4e23-ba6c-ecf55002fda0)

**Comment by sschmischke** [comment]
I can't use Chrome because of company restrictions. But in Edge and Firefox the self signed cert is valid.

![grafik](https://github.com/dynatrace-extensions/dynatrace-extensions-vscode/assets/127033402/46b04c9d-8725-40ef-a85d-9c648177d18a)

**Comment by sschmischke** [comment]
I've set it as system variable

```powershell
PS C:\> Get-Childitem -path env:NODE_EXTRA_CA_CERTS

Name                           Value
----                           -----
NODE_EXTRA_CA_CERTS            C:\dev\bin\DRVRootCA2018a.pem
``` 
but still get the same error when adding Dynatrace environment.

**Comment by radu-stefan-dt** [comment]
Right. Then I'm afraid there are no other options - currently this setup is not supported.
I'll create a ticket for improvement.

I wouldn't just add an option to disable SSL verification altogether, but I'm open to picking up an environment variable and pushing it forward like `NODE_EXTRA_CA_CERTS` is meant to do.

I just did a test and we have access to all the O/S environment variables.

**Comment by radu-stefan-dt** [comment]
I'm closing this issue. I've transferred the topic to #192
