### ISSUE TITLE
Support for self-signed SSL certificates in tenant connection

### ISSUE THREAD

**Issue by radu-stefan-dt** [dynatrace-extensions/dynatrace-extensions-vscode#192]
**Summary**
Many Dynatrace Managed users will have their Dynatrace Managed deployment secured with SSL through either self-signed certificates or certificates which their organization has re-signed after generating. In such cases our Dynatrace API client doesn't see this as a valid certificate and refuses to carry out requests over HTTPS.

Despite VS Code itself using the O/S trust store and NodeJS allowing for [`NODE_EXTRA_CA_CERTS`](https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file) environment variable to load additional CA certificates, VS Code extensions it seems do not inherit these settings. Our Axios client should allow for some configuration to compensate for this discrepancy.

**Current Behavior**
Dynatrace tenants with HTTPS connections going over self-signed certificates cannot be registered with our extension.

**Expected Behavior**
Similar to `NODE_EXTRA_CA_CERTS` we should have a simple mechanism (either environment variable or extension setting to load a custom CA file into our axios client).

**Comment by henryjb99** [comment]
Are there any plans to get this fixed? We are unable to use the Dynatrace Extension for VSCode to upgrade any of our 1.0 extensions due to this error.

**Comment by radu-stefan-dt** [comment]
Development has started on this feature. After additional research there will be 2 mechanisms implmented through extension settings:
- Path to a CA certificate file for a tenant. This will be used so that custom Authorities can be trusted and custom SSL Certificates can still be verified.
- Option to disable verification for a tenant. To also be able to support self-signed certificates (a.k.a. depth zero certificates, where Authority and sub-entity are the same) this requires disabling SSL verification altogether as Axios does not support any option for going around the self-signed certs through configuration; so checking must be fully disabled in this case.

**Comment by radu-stefan-dt** [comment]
Until the official documentation on Developer Portal gets updated, I'm sharing usage details here.
The extension has a new entry in the behavior configuration settings called "Tenant Connectivity Settings". This is a global (user) level setting and can only be edited in JSON format, so click "Edit in settings.json" to modify it.

![image](https://github.com/dynatrace-extensions/dynatrace-extensions-vscode/assets/16157796/3f168312-12ea-4a28-abcd-dcc912821c09)

The settings is an array of objects comprised of up to three details:
- `tenantUrl`: the URL of your tenant's endpoint. This is used to match on which requests we need to apply the other two details below.
- `certificatePath`: Path to the root CA file associated with that endpoint. This is a path on the disk from which we can read either a `.crt` or `.pem` file to add to the trusted CAs.
- `disableSSLVerification` (defaults to `false`): whether to disable SSL verification altogether or not. This option should only be enabled if the endpoint is using a self-signed certificate (where both the Root/CA and the Leaf/server are the same entity). In this case, Axios will simply not permit requests to go through unless verification is completely disabled.

Example entry from `settings.json`:
```json
{
    "dynatraceExtensions.tenantConnectivitySettings": [
        {
            "tenantUrl": "https://10.0.0.1:5555/e/my-tenant",
            "certificatePath": "C:\\Temp\\radu_custom.crt"
        },
        {
            "tenantUrl": "https://my.custom.endpoint/e/my-other-tenant",
            "disableSSLVerification": true
        }
    ]
}
```

**Comment by avinashpodisetti** [comment]
"dynatraceExtensions.tenantConnectivitySettings": [
    


I am still running into the same issue.. here is what i have in my settings.json file
    {
            "tenantUrl": "https://dt-managed-notprod.******.com/e/e1fc6b45-c7e7-4329-82c4-ef4b67d8a94f",
            "certificatePath":"/Users/*****/Library/Application Support/Code/User/workspaceStorage/a3e208e5a62162e200a539a06a885512/DynatracePlatformExtensions.dynatrace-extensions/certificates/ca.pem"
        }
    ],
