### ISSUE TITLE
Auto complete prometheus labels to use as dimensions

### ISSUE THREAD

**Issue by Mike997** [dynatrace-extensions/dynatrace-extensions-vscode#205]
**Summary**
Lower the risk of typos and having to go back and fourth between the yaml and the prometheus exporter by also bringing in the dimensions.

**Current vs. Expected Behavior**
Currently the insert based on the scraping of Prometheus only brings in the metric IDs. The improvement would also bring in the labels as dimensions.

**Additional context**
If the label already is added to the group/subgroup on a higher level, it should not be added again when inserting an individual metric.

**Comment by radu-stefan-dt** [comment]
@Mike997 - dimensions are all captured by default in prometheus...
The only reason people would add dimensions is to use filters.

Unless I'm missing something I think I'll close this issue.

**Comment by Mike997** [comment]
Makes sense, maybe include them so you can filter on them, but that will be confusing. Go ahead and close it.
________________________________
