### ISSUE TITLE
Add SaaS environments via friendly-name alias

### ISSUE THREAD

**Issue by d41k4n** [dynatrace-extensions/dynatrace-extensions-vscode#224]
**Summary**
Currently it's not always possible to add a new SaaS environment via an URL that uses a [user-friendly alias](https://docs.dynatrace.com/docs/manage/access-control/user-management-and-sso/manage-users-and-groups-with-saml/federation-concepts#glossary:~:text=%20It%20can%20have%20a%20user%2Dfriendly%20alias.%20The%20alias%20is%20unique%20and%20the%20environment%20can%20have%20at%20least%20one%20alias) instead of the environment ID.

**Current vs. Expected Behavior**
For example, if the "user-friendly alias" contains hyphens (which is legal) the URL will not pass the validation e.g.
![image](https://github.com/dynatrace-extensions/dynatrace-extensions-vscode/assets/6691087/877cad55-c19c-4c33-9d99-5bb7f9860d66)

The expectation is to allow any valid characters for the user-friendly environment alias.

**Additional context**
n.a.

**Comment by radu-stefan-dt** [comment]
Hi @d41k4n. Thanks for raising this issue.
