### ISSUE TITLE
[Bug]: Fix the barista icons URL

### ISSUE THREAD

**Issue by dlopes7** [dynatrace-extensions/dynatrace-extensions-vscode#233]
### Description

The URL as moved to https://raw.githubusercontent.com/dynatrace-oss/barista/master/docs/barista-icons/icons.json so we should also adapt to enable autocomplete again

### Steps to reproduce

Can't load barista icons if you are not in the dynatrace VPN

### Support information

- [ ] Screenshots
- [ ] Extension manifest file
- [ ] YAML snippets
- [X] Support archive ([see here](https://developer.dynatrace.com/extensions-v2/dynatrace-extensions-vscode/troubleshooting/#collect-a-log-archive))

**Comment by radu-stefan-dt** [comment]
Damn you are quick
