### ISSUE TITLE
[Bug]: JMX 1.0 to 2.0 extension conversion

### ISSUE THREAD

**Issue by APMGitHub** [dynatrace-extensions/dynatrace-extensions-vscode#251]
### Description

Seeing issue when converting JMX 1.0 extension with metric cards attributes. After converting to JMX 2.0 extension, I expected to see the metric charts at the host level. You can see the other JMX Kafka extensions displayed in screen shot below. I attached the working yaml data source and the JMX extension that we see issues with below. As you can see there is a difference on how the Chart cards and Metric table cards are configured from the working and non working yaml. I have tried several conversions on the jmx.kafkaeventmetrics.metric and still not seeing the Metric table cards at the Host level.

## Working yaml:

jmx:
  groups:
    - group: jmx
      subgroups:
        - subgroup: kafka.producer:client-id=*,node-id=*,type=*,*
          query: kafka.producer:client-id=*,node-id=*,type=*,*
          metrics:
            - key: jmx.kafka.perbroker.metric_request_size_max_1684846060686
              value: attribute:request-size-max
              type: gauge
            - key: jmx.kafka.perbroker.metric_response_rate_1684846119168
              value: attribute:response-rate
              type: gauge
          dimensions:
            - key: node-id
              value: property:node-id
screens:
  - entityType: PROCESS_GROUP_INSTANCE
    detailsInjections:
      - type: METRIC_TABLE
        key: metrictable-kafka_perbroker-metrics
        conditions:
          - metricAvailable|metric=dsfm:extension.status:filter(and(eq("dt.extension.name","custom:jmx.kafka.perbroker"),in("dt.entity.host",
            entitySelector("type(host),toRelationships.isProcessOf(entityId($(entityId)))"))))|lastWrittenWithinDays=5
          - entityAttribute|softwareTechnologies=KAFKA
    chartsCards: []
    metricTableCards:
      - key: metrictable-kafka_perbroker-metrics
        pageSize: 5
        displayName: Kafka_perBroker metrics
        numberOfVisibleCharts: 2
        hideEmptyCharts: true
        displayCharts: true
        enableDetailsExpandability: true
        charts:
          - displayName: request-size-max
            visualizationType: GRAPH_CHART
            graphChartConfig:
              stacked: false
              metrics:

## Non-working yaml:

jmx:
  groups:
    - group: jmx
      subgroups:
        - subgroup: kafka.consumer:type=consumer-fetch-manager-metrics,*
          query: kafka.consumer:type=consumer-fetch-manager-metrics,*
          metrics:
            - key: jmx.kafkaeventmetrics.metric_fetch_latency_avg_1679590136515
              value: attribute:fetch-latency-avg
              type: gauge
            - key: jmx.kafkaeventmetrics.metric_fetch_rate_1679590196037
              value: attribute:fetch-rate
              type: gauge
            - key: jmx.kafkaeventmetrics.metric_fetch_size_avg_1679590223415
              value: attribute:fetch-size-avg
              type: gauge
            - key: jmx.kafkaeventmetrics.metric_records_consumed_rate_1679590250049
              value: attribute:records-consumed-rate
              type: gauge
            - key: jmx.kafkaeventmetrics.metric_records_per_request_avg_1679590270514
              value: attribute:records-per-request-avg
              type: gauge
        - subgroup: kafka.consumer:type=consumer-coordinator-metrics,*
          query: kafka.consumer:type=consumer-coordinator-metrics,*
          metrics:
            - key: jmx.kafkaeventmetrics.metric_commit_latency_avg_1679590420271
              value: attribute:commit-latency-avg
              type: gauge
            - key: jmx.kafkaeventmetrics.metric_commit_rate_1679590317230
              value: attribute:commit-rate
              type: gauge
            - key: jmx.kafkaeventmetrics.metric_join_rate_1679590487292
              value: attribute:join-rate
              type: gauge
            - key: jmx.kafkaeventmetrics.metric_join_time_avg_1679590526034
              value: attribute:join-time-avg
              type: gauge
        - subgroup: kafka.consumer:type=consumer-metrics,*
          query: kafka.consumer:type=consumer-metrics,*
          metrics:
            - key: jmx.kafkaeventmetrics.metric_connection_count_1679590547700
              value: attribute:connection-count
              type: gauge
screens:
  - entityType: PROCESS_GROUP_INSTANCE
    detailsInjections:
      - type: CHART_GROUP
        key: chartgroup-kafkaeventmetrics-metrics
        conditions:
          - metricAvailable|metric=dsfm:extension.status:filter(and(eq("dt.extension.name","custom:jmx.kafkaeventmetrics"),in("dt.entity.host",
            entitySelector("type(host),toRelationships.isProcessOf(entityId($(entityId)))"))))|lastWrittenWithinDays=5

    chartsCards:
      - key: chartgroup-kafkaeventmetrics-metrics
        displayName: KafkaEventMetrics metrics
        numberOfVisibleCharts: 3
        chartsInRow: 3
        mode: NORMAL
        hideEmptyCharts: true
        charts:
          - displayName: fetch-latency-avg
            visualizationType: GRAPH_CHART
              stacked: false
              metrics:

            graphChartConfig:![jmxKafkaxtnview](https://github.com/user-attachments/assets/a575a194-3731-4a3f-aa92-a6a3eec569dd)

### Steps to reproduce

Enable workspace for JMX 2.0 extension in VSCode
Pick JMX source
converted

### Support information

- [X] Screenshots
- [ ] Extension manifest file
- [ ] YAML snippets
- [X] Support archive ([see here](https://developer.dynatrace.com/extensions-v2/dynatrace-extensions-vscode/troubleshooting/#collect-a-log-archive))

**Comment by radu-stefan-dt** [comment]
Hi @APMGitHub 
Could you please explain what the issue is and what is your expected result?
It's very difficult to understand from the original description

**Comment by APMGitHub** [comment]
Hi,

I updated the description with more details to the issue we are seeing.

**Comment by radu-stefan-dt** [comment]
Neither of those YAMLs should produce any content on the Host screen.
Both of them define the cards for `PROCESS_GROUP_INSTANCE` entity only. So that would be the actual Kafka process.

Would you mind sharing the original 1.0 JSON file you're trying to convert?

**Comment by APMGitHub** [comment]
[plugin.json](https://github.com/user-attachments/files/16677942/plugin.json)
[plugin.json](https://github.com/user-attachments/files/16677948/plugin.json)
Here are the json for both the working and non working.

**Comment by radu-stefan-dt** [comment]
Thank you for sharing the JSON files. I am still investigating the issue.

**Comment by radu-stefan-dt** [comment]
Apologies for the slow progress. Having looked at the conversion the mechanism this works as expected.

Given your issue is on the extension Host, I would suggest analysing the condition that those cards evaluate when choosing whether to display or not:

```yaml
conditions:
  - metricAvailable|metric=dsfm:extension.status:filter(and(eq("dt.extension.name","custom:jmx.kafkaeventmetrics"),in("dt.entity.host",
            entitySelector("entityId($(entityId))"))))|lastWrittenWithinDays=5
```

Essentially, we're looking for the metric `dsfm:extension.status` to have registered a datapoint in the last 5 days when filtered by dimension `dt.extension.name` with value `custom:jmx.kafkaeventmetrics` and `dt.entity.host` with the ID of the Host you're viewing on screen.

`custom:jmx.kafkaeventmetrics` is the auto-generated name for the extension based on the `plugin.json` files you shared. If this was modified at all, it needs to be modified in the condition too.

**Comment by radu-stefan-dt** [comment]
As a next step, could you please use the Data Explorer (from main menu) set on "Advanced mode" (top right corner) and share the results of the following metric selectors?

- Selector: `dsfm:extension.status:splitBy("dt.extension.name")`
  Questions:
    - Do you get any data?
    - Does your kafkaeventmetrics extension show up?

- Selector (replace `HOST-XXXXXXXXX` with the ID of your expected Host):
    ```
    dsfm:extension.status:splitBy("dt.extension.name", 
    "dt.entity.host"):filter(in("dt.entity.host", entitySelector("entityId(~"HOST- 
    XXXXXXXXX~")")))
    ```
  Questions:
    - Do you get any data?

**Comment by APMGitHub** [comment]
![ito034977-jmx kafkaeventmetric](https://github.com/user-attachments/assets/d96e9008-22db-4b64-836c-ed1f63377373)
![jmx kafka extensions](https://github.com/user-attachments/assets/671c4b54-7c2f-45d5-9232-6e6e65064caf)

Here are the screen shoots of the two queries. I do see the jmx.kafkaeventmetrics extension on both.

**Comment by radu-stefan-dt** [comment]
So, as I see it the YAMLs sent (as well as my own conversion from the JSON sent) are referencing `custom:jmx.kafkaeventmetrics`

I cannot see this name appear in your screenshots.

It is either `custom:ford.jmx.kafkaeventmetrics` or `custom:xtn.jmx.kafkaeventmetrics`

This will cause the data to not appear on screens.

**Comment by radu-stefan-dt** [comment]
Can you confirm:
1. What is the name of the extension you are troubleshooting?
2. What is the name of the extension in your YAML in the "condition" attribute?

These needs to match with the metric data to be able to have charts/tables showing up correctly on Host and Process screens.

**Comment by APMGitHub** [comment]
Sorry for confusion on the yaml and json I sent in case. I did so much different testing on the JMX conversions I had multiple configurations. I am adding the following JSON and YAML that is currently enabled. This is the showing up in the above data explorer queries as well.

[
  {
    "value": {
      "enabled": true,
      "description": "ito034977.hosts.cloud.ford.com",
      "version": "2.0.3",
      "activationTags": []
    },
    "scope": "HOST-3E438BEDA3341A5C"
  }
]

Yaml:
name: custom:ford.xtn.jmx.kafkaeventmetrics
version: 2.0.3
minDynatraceVersion: 1.275.0
author:
  name: Joel Mozo
jmx:
  groups:
    - group: jmx
      subgroups:
        - subgroup: kafka.consumer:type=consumer-fetch-manager-metrics,*
          query: kafka.consumer:type=consumer-fetch-manager-metrics,*
          metrics:
            - key: jmx.kafkaeventmetrics.metric_fetch_latency_avg_1679590136515
              value: attribute:fetch-latency-avg
              type: gauge
            - key: jmx.kafkaeventmetrics.metric_fetch_rate_1679590196037
              value: attribute:fetch-rate
              type: gauge
            - key: jmx.kafkaeventmetrics.metric_fetch_size_avg_1679590223415
              value: attribute:fetch-size-avg
              type: gauge
            - key: jmx.kafkaeventmetrics.metric_records_consumed_rate_1679590250049
              value: attribute:records-consumed-rate
              type: gauge
            - key: jmx.kafkaeventmetrics.metric_records_per_request_avg_1679590270514
              value: attribute:records-per-request-avg
              type: gauge
        - subgroup: kafka.consumer:type=consumer-coordinator-metrics,*
          query: kafka.consumer:type=consumer-coordinator-metrics,*
          metrics:
            - key: jmx.kafkaeventmetrics.metric_commit_latency_avg_1679590420271
              value: attribute:commit-latency-avg
              type: gauge
            - key: jmx.kafkaeventmetrics.metric_commit_rate_1679590317230
              value: attribute:commit-rate
              type: gauge
            - key: jmx.kafkaeventmetrics.metric_join_rate_1679590487292
              value: attribute:join-rate
              type: gauge
            - key: jmx.kafkaeventmetrics.metric_join_time_avg_1679590526034
              value: attribute:join-time-avg
              type: gauge
        - subgroup: kafka.consumer:type=consumer-metrics,*
          query: kafka.consumer:type=consumer-metrics,*
          metrics:
            - key: jmx.kafkaeventmetrics.metric_connection_count_1679590547700
              value: attribute:connection-count
              type: gauge
screens:
  - entityType: PROCESS_GROUP_INSTANCE
    detailsInjections:
      - type: CHART_GROUP
        key: chartgroup-kafkaeventmetrics-metrics
        conditions:
          - metricAvailable|metric=dsfm:extension.status:filter(and(eq("dt.extension.name","custom:jmx.kafkaeventmetrics"),in("dt.entity.host",
            entitySelector("type(host),toRelationships.isProcessOf(entityId($(entityId)))"))))|lastWrittenWithinDays=5

    chartsCards:
      - key: chartgroup-kafkaeventmetrics-metrics
        displayName: KafkaEventMetrics metrics
        numberOfVisibleCharts: 3
        chartsInRow: 3
        mode: NORMAL
        hideEmptyCharts: true
        charts:
          - displayName: fetch-latency-avg
            visualizationType: GRAPH_CHART
            graphChartConfig:
              stacked: false
              metrics:
                - metricSelector: jmx.kafkaeventmetrics.metric_fetch_latency_avg_1679590136515:splitBy("dt.entity.process_group_instance")
                  visualization:
                    displayName: fetch-latency-avg
          - displayName: fetch-rate
            visualizationType: GRAPH_CHART
            graphChartConfig:
              stacked: false
              metrics:
                - metricSelector: jmx.kafkaeventmetrics.metric_fetch_rate_1679590196037:splitBy("dt.entity.process_group_instance")
                  visualization:
                    displayName: fetch-rate
          - displayName: fetch-size-avg
            visualizationType: GRAPH_CHART
            graphChartConfig:
              stacked: false
              metrics:
                - metricSelector: jmx.kafkaeventmetrics.metric_fetch_size_avg_1679590223415:splitBy("dt.entity.process_group_instance")
                  visualization:
                    displayName: fetch-size-avg
          - displayName: records-consumed-rate
            visualizationType: GRAPH_CHART
            graphChartConfig:
              stacked: false
              metrics:
                - metricSelector: jmx.kafkaeventmetrics.metric_records_consumed_rate_1679590250049:splitBy("dt.entity.process_group_instance")
                  visualization:
                    displayName: records-consumed-rate
          - displayName: records-per-request-avg
            visualizationType: GRAPH_CHART
            graphChartConfig:
              stacked: false
              metrics:
                - metricSelector: jmx.kafkaeventmetrics.metric_records_per_request_avg_1679590270514:splitBy("dt.entity.process_group_instance")
                  visualization:
                    displayName: records-per-request-avg
          - displayName: commit-latency-avg
            visualizationType: GRAPH_CHART
            graphChartConfig:
              stacked: false
              metrics:
                - metricSelector: jmx.kafkaeventmetrics.metric_commit_latency_avg_1679590420271:splitBy("dt.entity.process_group_instance")
                  visualization:
                    displayName: commit-latency-avg
          - displayName: commit-rate
            visualizationType: GRAPH_CHART
            graphChartConfig:
              stacked: false
              metrics:
                - metricSelector: jmx.kafkaeventmetrics.metric_commit_rate_1679590317230:splitBy("dt.entity.process_group_instance")
                  visualization:
                    displayName: commit-rate
          - displayName: join-rate
            visualizationType: GRAPH_CHART
            graphChartConfig:
              stacked: false
              metrics:
                - metricSelector: jmx.kafkaeventmetrics.metric_join_rate_1679590487292:splitBy("dt.entity.process_group_instance")
                  visualization:
                    displayName: join-rate
          - displayName: join-time-avg
            visualizationType: GRAPH_CHART
            graphChartConfig:
              stacked: false
              metrics:
                - metricSelector: jmx.kafkaeventmetrics.metric_join_time_avg_1679590526034:splitBy("dt.entity.process_group_instance")
                  visualization:
                    displayName: join-time-avg
          - displayName: connection-count
            visualizationType: GRAPH_CHART
            graphChartConfig:
              stacked: false
              metrics:
                - metricSelector: jmx.kafkaeventmetrics.metric_connection_count_1679590547700:splitBy("dt.entity.process_group_instance")
                  visualization:
                    displayName: connection-count
    metricTableCards: []
  - entityType: HOST
    detailsInjections:
      - type: METRIC_TABLE
        key: metrictable-jmx-jmx_kafkaeventmetrics
        conditions:
          - metricAvailable|metric=dsfm:extension.status:filter(and(eq("dt.extension.name","custom:jmx.kafkaeventmetrics"),in("dt.entity.host",
            entitySelector("entityId($(entityId))"))))|lastWrittenWithinDays=5
    metricTableCards:
      - key: metrictable-jmx-jmx_kafkaeventmetrics
        displayName: JMX Metrics (jmx.kafkaeventmetrics)
        pageSize: 5
        numberOfVisibleCharts: 3
        hideEmptyCharts: true
        displayCharts: true
        enableDetailsExpandability: true
        charts:
          - displayName: fetch-latency-avg
            visualizationType: GRAPH_CHART
            graphChartConfig:
              stacked: false
              metrics:
                - metricSelector: jmx.kafkaeventmetrics.metric_fetch_latency_avg_1679590136515:splitBy()
                  metricSelectorSort: jmx.kafkaeventmetrics.metric_fetch_latency_avg_1679590136515$(entityFilter)$(userFilter):splitBy("dt.entity.process_group_instance"):avg$(aggregation):last:sort(value(avg,$(sortOrder))):names
                  metricSelectorDetailed: jmx.kafkaeventmetrics.metric_fetch_latency_avg_1679590136515$(entityFilter)$(userFilter):splitBy("dt.entity.process_group_instance")$(aggregation)
                  visualization:
                    displayName: fetch-latency-avg
          - displayName: fetch-rate
            visualizationType: GRAPH_CHART
            graphChartConfig:
              stacked: false
              metrics:
                - metricSelector: jmx.kafkaeventmetrics.metric_fetch_rate_1679590196037:splitBy()
                  metricSelectorSort: jmx.kafkaeventmetrics.metric_fetch_rate_1679590196037$(entityFilter)$(userFilter):splitBy("dt.entity.process_group_instance"):avg$(aggregation):last:sort(value(avg,$(sortOrder))):names
                  metricSelectorDetailed: jmx.kafkaeventmetrics.metric_fetch_rate_1679590196037$(entityFilter)$(userFilter):splitBy("dt.entity.process_group_instance")$(aggregation)
                  visualization:
                    displayName: fetch-rate
          - displayName: fetch-size-avg
            visualizationType: GRAPH_CHART
            graphChartConfig:
              stacked: false
              metrics:
                - metricSelector: jmx.kafkaeventmetrics.metric_fetch_size_avg_1679590223415:splitBy()
                  metricSelectorSort: jmx.kafkaeventmetrics.metric_fetch_size_avg_1679590223415$(entityFilter)$(userFilter):splitBy("dt.entity.process_group_instance"):avg$(aggregation):last:sort(value(avg,$(sortOrder))):names
                  metricSelectorDetailed: jmx.kafkaeventmetrics.metric_fetch_size_avg_1679590223415$(entityFilter)$(userFilter):splitBy("dt.entity.process_group_instance")$(aggregation)
                  visualization:
                    displayName: fetch-size-avg
          - displayName: records-consumed-rate
            visualizationType: GRAPH_CHART
            graphChartConfig:
              stacked: false
              metrics:
                - metricSelector: jmx.kafkaeventmetrics.metric_records_consumed_rate_1679590250049:splitBy()
                  metricSelectorSort: jmx.kafkaeventmetrics.metric_records_consumed_rate_1679590250049$(entityFilter)$(userFilter):splitBy("dt.entity.process_group_instance"):avg$(aggregation):last:sort(value(avg,$(sortOrder))):names
                  metricSelectorDetailed: jmx.kafkaeventmetrics.metric_records_consumed_rate_1679590250049$(entityFilter)$(userFilter):splitBy("dt.entity.process_group_instance")$(aggregation)
                  visualization:
                    displayName: records-consumed-rate
          - displayName: records-per-request-avg
            visualizationType: GRAPH_CHART
            graphChartConfig:
              stacked: false
              metrics:
                - metricSelector: jmx.kafkaeventmetrics.metric_records_per_request_avg_1679590270514:splitBy()
                  metricSelectorSort: jmx.kafkaeventmetrics.metric_records_per_request_avg_1679590270514$(entityFilter)$(userFilter):splitBy("dt.entity.process_group_instance"):avg$(aggregation):last:sort(value(avg,$(sortOrder))):names
                  metricSelectorDetailed: jmx.kafkaeventmetrics.metric_records_per_request_avg_1679590270514$(entityFilter)$(userFilter):splitBy("dt.entity.process_group_instance")$(aggregation)
                  visualization:
                    displayName: records-per-request-avg
          - displayName: commit-latency-avg
            visualizationType: GRAPH_CHART
            graphChartConfig:
              stacked: false
              metrics:
                - metricSelector: jmx.kafkaeventmetrics.metric_commit_latency_avg_1679590420271:splitBy()
                  metricSelectorSort: jmx.kafkaeventmetrics.metric_commit_latency_avg_1679590420271$(entityFilter)$(userFilter):splitBy("dt.entity.process_group_instance"):avg$(aggregation):last:sort(value(avg,$(sortOrder))):names
                  metricSelectorDetailed: jmx.kafkaeventmetrics.metric_commit_latency_avg_1679590420271$(entityFilter)$(userFilter):splitBy("dt.entity.process_group_instance")$(aggregation)
                  visualization:
                    displayName: commit-latency-avg
          - displayName: commit-rate
            visualizationType: GRAPH_CHART
            graphChartConfig:
              stacked: false
              metrics:
                - metricSelector: jmx.kafkaeventmetrics.metric_commit_rate_1679590317230:splitBy()
                  metricSelectorSort: jmx.kafkaeventmetrics.metric_commit_rate_1679590317230$(entityFilter)$(userFilter):splitBy("dt.entity.process_group_instance"):avg$(aggregation):last:sort(value(avg,$(sortOrder))):names
                  metricSelectorDetailed: jmx.kafkaeventmetrics.metric_commit_rate_1679590317230$(entityFilter)$(userFilter):splitBy("dt.entity.process_group_instance")$(aggregation)
                  visualization:
                    displayName: commit-rate
          - displayName: join-rate
            visualizationType: GRAPH_CHART
            graphChartConfig:
              stacked: false
              metrics:
                - metricSelector: jmx.kafkaeventmetrics.metric_join_rate_1679590487292:splitBy()
                  metricSelectorSort: jmx.kafkaeventmetrics.metric_join_rate_1679590487292$(entityFilter)$(userFilter):splitBy("dt.entity.process_group_instance"):avg$(aggregation):last:sort(value(avg,$(sortOrder))):names
                  metricSelectorDetailed: jmx.kafkaeventmetrics.metric_join_rate_1679590487292$(entityFilter)$(userFilter):splitBy("dt.entity.process_group_instance")$(aggregation)
                  visualization:
                    displayName: join-rate
          - displayName: join-time-avg
            visualizationType: GRAPH_CHART
            graphChartConfig:
              stacked: false
              metrics:
                - metricSelector: jmx.kafkaeventmetrics.metric_join_time_avg_1679590526034:splitBy()
                  metricSelectorSort: jmx.kafkaeventmetrics.metric_join_time_avg_1679590526034$(entityFilter)$(userFilter):splitBy("dt.entity.process_group_instance"):avg$(aggregation):last:sort(value(avg,$(sortOrder))):names
                  metricSelectorDetailed: jmx.kafkaeventmetrics.metric_join_time_avg_1679590526034$(entityFilter)$(userFilter):splitBy("dt.entity.process_group_instance")$(aggregation)
                  visualization:
                    displayName: join-time-avg
          - displayName: connection-count
            visualizationType: GRAPH_CHART
            graphChartConfig:
              stacked: false
              metrics:
                - metricSelector: jmx.kafkaeventmetrics.metric_connection_count_1679590547700:splitBy()
                  metricSelectorSort: jmx.kafkaeventmetrics.metric_connection_count_1679590547700$(entityFilter)$(userFilter):splitBy("dt.entity.process_group_instance"):avg$(aggregation):last:sort(value(avg,$(sortOrder))):names
                  metricSelectorDetailed: jmx.kafkaeventmetrics.metric_connection_count_1679590547700$(entityFilter)$(userFilter):splitBy("dt.entity.process_group_instance")$(aggregation)
                  visualization:
                    displayName: connection-count
metrics:
  - key: jmx.kafkaeventmetrics.metric_fetch_latency_avg_1679590136515
    metadata:
      displayName: fetch-latency-avg
      description: fetch-latency-avg
      unit: Count
      sourceEntityType: process_group_instance
      tags:
        - JMX
  - key: func:jmx.kafkaeventmetrics.metric_fetch_latency_avg_1679590136515_persec
    metadata:
      displayName: fetch-latency-avg (per second)
      description: fetch-latency-avg expressed as a rate per second
      unit: PerSecond
      tags:
        - JMX
    query:
      metricSelector: jmx.kafkaeventmetrics.metric_fetch_latency_avg_1679590136515 / (10)
  - key: jmx.kafkaeventmetrics.metric_fetch_rate_1679590196037
    metadata:
      displayName: fetch-rate
      description: fetch-rate
      unit: Count
      sourceEntityType: process_group_instance
      tags:
        - JMX
  - key: func:jmx.kafkaeventmetrics.metric_fetch_rate_1679590196037_persec
    metadata:
      displayName: fetch-rate (per second)
      description: fetch-rate expressed as a rate per second
      unit: PerSecond
      tags:
        - JMX
    query:
      metricSelector: jmx.kafkaeventmetrics.metric_fetch_rate_1679590196037 / (10)
  - key: jmx.kafkaeventmetrics.metric_fetch_size_avg_1679590223415
    metadata:
      displayName: fetch-size-avg
      description: fetch-size-avg
      unit: BytePerSecond
      sourceEntityType: process_group_instance
      tags:
        - JMX
  - key: func:jmx.kafkaeventmetrics.metric_fetch_size_avg_1679590223415_persec
    metadata:
      displayName: fetch-size-avg (per second)
      description: fetch-size-avg expressed as a rate per second
      unit: BytePerSecondPerSecond
      tags:
        - JMX
    query:
      metricSelector: jmx.kafkaeventmetrics.metric_fetch_size_avg_1679590223415 / (10)
  - key: jmx.kafkaeventmetrics.metric_records_consumed_rate_1679590250049
    metadata:
      displayName: records-consumed-rate
      description: records-consumed-rate
      unit: Count
      sourceEntityType: process_group_instance
      tags:
        - JMX
  - key: func:jmx.kafkaeventmetrics.metric_records_consumed_rate_1679590250049_persec
    metadata:
      displayName: records-consumed-rate (per second)
      description: records-consumed-rate expressed as a rate per second
      unit: PerSecond
      tags:
        - JMX
    query:
      metricSelector: jmx.kafkaeventmetrics.metric_records_consumed_rate_1679590250049 / (10)
  - key: jmx.kafkaeventmetrics.metric_records_per_request_avg_1679590270514
    metadata:
      displayName: records-per-request-avg
      description: records-per-request-avg
      unit: Count
      sourceEntityType: process_group_instance
      tags:
        - JMX
  - key: func:jmx.kafkaeventmetrics.metric_records_per_request_avg_1679590270514_persec
    metadata:
      displayName: records-per-request-avg (per second)
      description: records-per-request-avg expressed as a rate per second
      unit: PerSecond
      tags:
        - JMX
    query:
      metricSelector: jmx.kafkaeventmetrics.metric_records_per_request_avg_1679590270514 / (10)
  - key: jmx.kafkaeventmetrics.metric_commit_latency_avg_1679590420271
    metadata:
      displayName: commit-latency-avg
      description: commit-latency-avg
      unit: MilliSecond
      sourceEntityType: process_group_instance
      tags:
        - JMX
  - key: func:jmx.kafkaeventmetrics.metric_commit_latency_avg_1679590420271_persec
    metadata:
      displayName: commit-latency-avg (per second)
      description: commit-latency-avg expressed as a rate per second
      unit: MilliSecondPerSecond
      tags:
        - JMX
    query:
      metricSelector: jmx.kafkaeventmetrics.metric_commit_latency_avg_1679590420271 / (10)
  - key: jmx.kafkaeventmetrics.metric_commit_rate_1679590317230
    metadata:
      displayName: commit-rate
      description: commit-rate
      unit: Count
      sourceEntityType: process_group_instance
      tags:
        - JMX
  - key: func:jmx.kafkaeventmetrics.metric_commit_rate_1679590317230_persec
    metadata:
      displayName: commit-rate (per second)
      description: commit-rate expressed as a rate per second
      unit: PerSecond
      tags:
        - JMX
    query:
      metricSelector: jmx.kafkaeventmetrics.metric_commit_rate_1679590317230 / (10)
  - key: jmx.kafkaeventmetrics.metric_join_rate_1679590487292
    metadata:
      displayName: join-rate
      description: join-rate
      unit: Count
      sourceEntityType: process_group_instance
      tags:
        - JMX
  - key: func:jmx.kafkaeventmetrics.metric_join_rate_1679590487292_persec
    metadata:
      displayName: join-rate (per second)
      description: join-rate expressed as a rate per second
      unit: PerSecond
      tags:
        - JMX
    query:
      metricSelector: jmx.kafkaeventmetrics.metric_join_rate_1679590487292 / (10)
  - key: jmx.kafkaeventmetrics.metric_join_time_avg_1679590526034
    metadata:
      displayName: join-time-avg
      description: join-time-avg
      unit: MilliSecond
      sourceEntityType: process_group_instance
      tags:
        - JMX
  - key: func:jmx.kafkaeventmetrics.metric_join_time_avg_1679590526034_persec
    metadata:
      displayName: join-time-avg (per second)
      description: join-time-avg expressed as a rate per second
      unit: MilliSecondPerSecond
      tags:
        - JMX
    query:
      metricSelector: jmx.kafkaeventmetrics.metric_join_time_avg_1679590526034 / (10)
  - key: jmx.kafkaeventmetrics.metric_connection_count_1679590547700
    metadata:
      displayName: connection-count
      description: connection-count
      unit: Count
      sourceEntityType: process_group_instance
      tags:
        - JMX
  - key: func:jmx.kafkaeventmetrics.metric_connection_count_1679590547700_persec
    metadata:
      displayName: connection-count (per second)
      description: connection-count expressed as a rate per second
      unit: PerSecond
      tags:
        - JMX
    query:
      metricSelector: jmx.kafkaeventmetrics.metric_connection_count_1679590547700 / (10)

**Comment by APMGitHub** [comment]
![image](https://github.com/user-attachments/assets/a0b3e286-5ae5-483c-926f-0a388896bf41)

**Comment by radu-stefan-dt** [comment]
Ok. So this is the problem actually.

In the YAML shared there is `name: custom:ford.xtn.jmx.kafkaeventmetrics` - this registers the extension with this name/ID.

However, later when charts are defined - all the conditions are like `:filter(and(eq("dt.extension.name","custom:jmx.kafkaeventmetrics"),` which basically add filtering to based on a different extension name.

I assume that the v1 JSON was first converted, and then the name of the extension was changed - but only in the `name:` attribute and not globally.

Please modify `custom:jmx.kafkaeventmetrics` (old, auto-generated name) to `custom:ford.xtn.jmx.kafkaeventmetrics` (new name) globally, on every occurrence.

**Comment by radu-stefan-dt** [comment]
Another issue that I think might be affecting it would be the keys of the chart group cards and metric table cards. Because you are working with variations of the same extension, the card keys might not be unique enough - e.g. `chartgroup-kafkaeventmetrics-metrics`

In Dynatrace, on a screen like Host or Process where cards are injected from extensions, they will appear once per ID. If the ID is not unique enough and multiple extensions define cards by the same ID, only the last one deployed will end up being displayed in the UI.
