### ISSUE TITLE
[Bug]: Visual Studio Code Marketplace broken link

### ISSUE THREAD

**Issue by felipmiguel** [dynatrace-extensions/dynatrace-extensions-vscode#253]
### Description

The link on the Visual Studio Marketplace that points to Dynatrace Developer portal is broken.
<img width="1044" alt="image" src="https://github.com/user-attachments/assets/ea550872-7c1f-45d1-8876-1c7742ad11dc">
Goes to
![image](https://github.com/user-attachments/assets/ecada010-837d-43ce-8f49-06f44664b7ae)

It also happens from VSCode extension page.

### Steps to reproduce

1. Go to Dynatrace Extensions page on the Visual Studio Code marketplace. https://marketplace.visualstudio.com/items?itemName=DynatracePlatformExtensions.dynatrace-extensions
2. Open the link to the Dynatrace documentation. See <img width="1044" alt="image" src="https://github.com/user-attachments/assets/ea550872-7c1f-45d1-8876-1c7742ad11dc">
3. The page is not found. See ![image](https://github.com/user-attachments/assets/ecada010-837d-43ce-8f49-06f44664b7ae)

### Support information

- [X] Screenshots
- [ ] Extension manifest file
- [ ] YAML snippets
- [X] Support archive ([see here](https://developer.dynatrace.com/extensions-v2/dynatrace-extensions-vscode/troubleshooting/#collect-a-log-archive))

**Comment by radu-stefan-dt** [comment]
Please use this link while we work on updating Marketplace - https://developer.dynatrace.com/develop/dynatrace-extensions-vscode/

**Comment by radu-stefan-dt** [comment]
The marketplace link has been updated with the latest release.
