### ISSUE TITLE
validate OID against provided MIB

### ISSUE THREAD

**Issue by dt-lizac** [dynatrace-extensions/dynatrace-extensions-vscode#98]
currently, it seems only generic OID can be validated. 
When specific MIB files are provided and placed inside "snmp" folder, they should be used to validate OIDs

**Comment by radu-stefan-dt** [comment]
This is a great suggestion, thanks Laurent!
In the meantime, if these highlights for "existence of this OID could not be verified" become too annoying, please use the settings to disable them on the workspace. Example [here](getRequiredDimensions).

**Comment by radu-stefan-dt** [comment]
This will be part of 2.0.0 release.

Features:
* MIB Files present in the `extension/snmp` folder will be loaded at startup and used for diagnostics, completions, and actions (similar to the current behvaior for public OIDs)
* An SNMP code lens appears over `snmp:` to allow quick import of MIB files
* Details about OIDs can be viewed by hovering over them in the extension manifest
  ![oid hover](https://github.com/dynatrace-extensions/dynatrace-extensions-vscode/assets/16157796/8c50d4b4-b88e-4be2-b729-539e69ad0f4c)

  ![oid diagnostic](https://github.com/dynatrace-extensions/dynatrace-extensions-vscode/assets/16157796/f45cc78f-bdb0-4194-a377-2473f6749e38)



Adjustments:
* The online database is still used as a fallback for any OID that wasn't available locally
* Loading a MIB File is only possible if all its dependencies (IMPORTS) are also loaded. The VSCode extension will come pre-loaded with some base MIB files:
    * RFC1155-SMI
    * RFC1158-MIB
    * RFC1212-MIB
    * RFC1213-MIB
    * SNMPv2-CONF
    * SNMPv2-MIB
    * SNMPv2-SMI
    * SNMPv2-TC
    * INET-ADDRESS-MIB
* Any dependency outside of these pre-loaded MIBs must be present in the `extension/snmp` folder
